name: Build Kernel Packages

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        psabi: [default]

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 4096
        swap-size-mb: 512
        remove-dotnet: 'true'
        remove-android: 'true'

    - uses: actions/checkout@v3

    - name: Set up Debian container
      uses: addnab/docker-run-action@v3
      with:
        image: docker.io/library/debian:trixie-slim
        options: -v ${{ github.workspace }}:/work
        run: |
          cd /work
          apt update; apt install -y --no-install-recommends fakeroot build-essential git wget openssl libssl-dev ca-certificates libncurses-dev zstd xz-utils flex libelf-dev bison bc debhelper rsync kmod cpio gpg pahole python3 devscripts 
          apt build-dep -y ./
          # openssl req -new -nodes -utf8 -sha512 -days 36500 -batch -x509 -config certs/default_x509.genkey -outform DER -out certs/signing_key.# x509 -keyout certs/signing_key.pem
          git config --global --add safe.directory /work
          CPU_CORES=$(($(grep -c processor < /proc/cpuinfo)*2))
          make deb-pkg -j"$CPU_CORES"
          mkdir assets
          mv ../*.deb assets/

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.job-name }}~${{ github.sha }}
        path: |
          assets/**
          !assets/*dbg*
        if-no-files-found: error