name: Build Kernel Packages

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        psabi: [default]

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 4096
        swap-size-mb: 512
        remove-dotnet: 'true'
        remove-android: 'true'

    - uses: actions/checkout@v4
      with:
        path: 'linux'

    - name: Set up Debian container
      uses: addnab/docker-run-action@v3
      with:
        image: docker.io/library/debian:trixie-slim
        options: -v ${{ github.workspace }}:/work
        run: |
          cd /work/linux
          apt update; apt install -y --no-install-recommends lsb-release fakeroot build-essential git wget openssl libssl-dev ca-certificates libncurses-dev zstd xz-utils flex libelf-dev bison bc debhelper rsync kmod cpio gpg pahole python3 devscripts 
          apt build-dep -y ./
          git config --global --add safe.directory /work/linux
          debuild -us -uc -b
          cd /work
          mkdir assets
          mv ./*.deb assets/
          mv ./*.orig.tar.gz assets/

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.job-name }}~${{ github.sha }}
        path: |
          assets/**
          !assets/*dbg*
        if-no-files-found: error
